config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :items, only: %i[index show]
  resources :sima, only: %i[create new]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  validates :price, :wholesale_price, numericality: { greater_than: 0 }, format: { with: /\A\d{1,3}(\.\d{1,2})?\z/ }
  validates :id, :sid, :balance, presence: true
  validates :balance, numericality: { greater_than: 0, only_integer: true }

  def short_name
    name[0, 50]
  end

  def photos_url
    agg_photos.map { |i| "#{base_photo_url}#{i}/700.jpg" }
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/controllers/sima_controller.rb
# frozen_string_literal: true

class SimaController < ApplicationController
  def new
  end

  def create
    sima = SimaApi.new(ENV['API_KEY'])
    resp = sima.get_item(params[:p])

    if resp[:message] != 'not found'
      ItemFromSima.create_item(resp)
    else
      render :new, flash: { alert: "Товар не найден" }
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/items/index.html.haml
%h1 Товары
%table
  %tr
    %th Артикул
    %th Название
    %th Оптовая цена
    %th Остаток
  - @items.each do |item|
    %tr
      %td #{link_to item.id, item_path(item.id)}
      %td #{item.short_name}
      %td #{item.wholesale_price.to_s}
      %td #{item.balance}

app/views/items/show.html.haml
%h1 #{@item.name}

%p Артикул: #{@item.sid}
%p ID СимаЛэнда: #{@item.id}
%p Описание: #{@item.description}
%p Оптовая цена: #{@item.wholesale_price}
%p Остаток: #{@item.balance}
%p Глубина упаковки: #{@item.box_depth}
%p Ширина упаковки: #{@item.box_height}
%p Высота упаковки: #{@item.box_width}
%p Глубина: #{@item.depth}
%p Высота: #{@item.height}
%p Ширина: #{@item.width}
%p Вес: #{@item.weight}
%p Ссылки на фото: 
- @item.photos_url.each do |a|
  %a(title=a href=a) Фото

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SimaOzon
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    = yield

app/views/sima/new.html.haml
%h1 Добавить товар по артикулу
= form_with url: sima_index_path, method: :pots do |f|
  = f.label :p, 'Артикул'
  = f.text_field :p
  = f.submit 